name: Preflight check for PRs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  preflight:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: ESLint
        run: npx eslint

      - name: Prettier
        run: npx prettier --check .

      - name: Typecheck
        run: npm run check-types

      - name: Tests
        run: npm run test
